### ISSUE TITLE
Shift/caps

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#114]
Add shift and caps lock

**Comment by 7imbrook** [comment]
@piperchester in ABTouchLayer three sounds need to be added, one for shift on, caps on, and nothing. The states change [here](https://github.com/RITAccess/accessbraille/blob/master/AccessBraille/AccessBraille/ABTouchLayer.m#L176-L183)

**Comment by piperchester** [comment]
I'm on it.

**Comment by 7imbrook** [comment]
+1
