### ISSUE TITLE
Stop Speaking After Mode Exit

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessbraille#116]
When you access Text Adventure, the initial instructions begin to play. This is exactly what we want to happen, but if the user pulls out the nav menu to select a different mode, e.g. Settings, the instructions are still being spoken.

**Comment by 7imbrook** [comment]
I will add stop speaking methods, then reassign to @piperchester.

**Comment by 7imbrook** [comment]
use `-stopSpeaking`
