### ISSUE TITLE
New menu gesture

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#158]
The main menu needs an activation gesture.

**Comment by piperchester** [comment]
Not sure how to implement this. I know you were having trouble thinking of something as well.

**Comment by 7imbrook** [comment]
It's a matter of adding a gesture recognizer to the child view controller when it is added to the subview. [See Here](https://github.com/RITAccess/accessbraille/blob/master/AccessBraille/AccessBraille/NavigationContainer.m#L58-L81)

**Comment by piperchester** [comment]
Right, that's where I was working. My problem was that with every sub view controller, I'm not sure where to have the method that needs to respond to the gesture, for example:

`- (void)willHandleDoubleTap:(UIGestureRecognizer *)gesture { }`

I don't want to repeat code; where will this be implemented? That's the main issue I was having.

**Comment by 7imbrook** [comment]
Add it to the container controller, activate the menu in there. The child will never know what happened.
