### ISSUE TITLE
Change Backspace Sound

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessbraille#162]
Ensure this sound is being handled by system volume.

**Comment by piperchester** [comment]
I'm handling volume control using `AVPlayer` as opposed to `AudioServicePlaySystemSound` in TextAdventure. I'm passing `NSURL`s to the `AVPlayer` during initialization. 

Do we want to move towards `AVPlayer` in the framework, @7imbrook? If so, I can implement it.

**Comment by 7imbrook** [comment]
Yes
