### ISSUE TITLE
Reimplement About View

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessbraille#188]
I really don't think the about view should be a web view, mainly because the user should be able to read the about view regardless of whether or not they have an internet connection. 

Thoughts?

**Comment by piperchester** [comment]
Never mind - already taken care of! :+1:

**Comment by 7imbrook** [comment]
It's not connecting to the internet... It's a webview rendering a .rtf file. Still fully accessible.

**Comment by piperchester** [comment]
Yeah - that was my bad. Still early.

**Comment by piperchester** [comment]
Are you trolling this issue or was that just a bug with GitHub... :octocat:
