### ISSUE TITLE
Add Workflow to Wiki

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#189]
Workflow is going to be the same as AccessMath, work on the development branch and stop pushing to master.

**Comment by piperchester** [comment]
:ok_hand:  - doesn't need to be an issue though, just hound me on Facebook/SMS/Snapchat/MySpace

**Comment by 7imbrook** [comment]
~~Wow coming from mr I open issues for everything. Just wanted to notify you and maybe I want to make this an issue!~~
Update: Add workflow from AccessMath to AccessBraille Wiki

**Comment by piperchester** [comment]
Better :+1:

**Comment by piperchester** [comment]
Added the _beautiful_ ASCII workflow chart from AccessMath. Closing.
