### ISSUE TITLE
Changing functionality

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#193]
Backspace is incorrect, along with shift and caps. Here's how it should work:
- [x] Backspace is on the left side, tap once for a single backspace
- [x] Shift by holding down (or pressing with) the space left of the keyboard, the same space as backspace
- [x] Enter can be added to the right of the keyboard
- [x] Space is below the keys

**Comment by piperchester** [comment]
Cool cool :+1: . Is this the feedback from STEMX? #182

**Comment by 7imbrook** [comment]
some of it
