### ISSUE TITLE
AssetMacros: queueEntry error

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#194]
I dont know where this is coming from but its an issue.
`AssertMacros: queueEntry,  file: /SourceCache/IOKitUser/IOKitUser 920.1.11/hid.subproj/IOHIDEventQueue.c, line: 512`

**Comment by 7imbrook** [comment]
This may just be me right now, @piperchester?

**Comment by piperchester** [comment]
Weird... definitely not having this issue, @7imbrook .

**Comment by 7imbrook** [comment]
Not getting it?

**Comment by piperchester** [comment]
No.

**Comment by 7imbrook** [comment]
Alright, then it's just on my branch. Looking into it

**Comment by piperchester** [comment]
:+1:

**Comment by 7imbrook** [comment]
Issue in beta, solution on apples dev forums. However they are down. Issue will be fixed in release. Closing
