### ISSUE TITLE
Rebuild menu architecture into separate views

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessbraille#215]
User feedback 2: users felt that our floating menu design was slightly confusing, mainly because of quick and easy it is to change screens. They'd prefer the simplicity of separate views (screens) for each app section.

**Comment by 7imbrook** [comment]
Do we want to keep the menu selection the same or redesign that?

**Comment by piperchester** [comment]
Not entirely clear, I'll ping Dr. Ludi

**Comment by piperchester** [comment]
Update: Instead of having a fluid scrolling sidebar for our menu, user feedback desires a more rigid, 1 item/swipe interface. 

For example, BT is the 1st option (highlighted in red) and is the only visible option on the screen, then the user swipes down and she can see Settings as the next option (only visible and highlighted in red)

**Comment by 7imbrook** [comment]
Ok, so let's swap the pan gr with just a swipe one. And when ever it triggers it will just move everything to start. I'll jump on this one.
