### ISSUE TITLE
Screenshots for Article

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#22]
We need to stage a screen shot or two for the research article.

Start Quote

Hi,

I know we still have a ways to go, but they want a screenshot of what we have for the article.  Can you send me one?

Here is what I'm thinking.  Have some text on there that showed that you entered some (something like 'Braille is fun') then have the screen also show the circles where the fingers can go.  That's really about all we can do at this point since the audio can't be portrayed.

Please try and get it to me this week as Kelly is about to go on maternity leave.

Thanks,
--Steph

End Quote

**Comment by piperchester** [comment]
Have taken the shots, and have sent them to Dr. Ludi.
