### ISSUE TITLE
Nav Menu Sounds

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#3]
Menus Sounds

**Comment by piperchester** [comment]
For starters, we need to have a sound for when the menu is opened.

**Comment by piperchester** [comment]
I've currently added a temporary sound for when the nav menu opens. Not on initial open off the main screen.

**Comment by piperchester** [comment]
Currently the sound plays multiple times when the nav bar is being slid open...It's a bug.

**Comment by piperchester** [comment]
Going to close this as pleasetest. We can come back to the voice bug later.
