### ISSUE TITLE
Voice Over Bugs

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#4]
slow, sometimes unresponsive

**Comment by piperchester** [comment]
As of now, we can't resolve this issue unless we use a different voice framework.

**Comment by piperchester** [comment]
Going to close as invalid and wontfix.

**Comment by 7imbrook** [comment]
We should start look at some non open source implementations maybe. I'm going to re open this as a rework.

**Comment by piperchester** [comment]
Definitely an issue. I'm unable to effectively speak the word, and then individual letters within Flash Card mode.
