### ISSUE TITLE
Discusion - Feature Branches

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#42]
Comment with branch name for feature and brief description and assign to someone. (GIF Required to lighten the mood)

**Comment by 7imbrook** [comment]
### brailleTyperImplementKeyboard - DONE

Implement the ABKeyboard framework into braille typer.
![http://i.imgur.com/DftsNYa.gif](http://i.imgur.com/DftsNYa.gif)
I've got this one

**Comment by 7imbrook** [comment]
### ABFramework

Continued work on the framework
![Just Win](http://i.imgur.com/dAtcCfH.gif)
I've got this one

**Comment by 7imbrook** [comment]
### flashCard

Flash card modes, main controller to select and use different flash card difficulties.
![](http://i.imgur.com/ClKc8N1.gif)
@piperchester can handle this

**Comment by 7imbrook** [comment]
### learnBraille

By stating finger positions and associating them with letter, the user can learn braille.
![](http://i.imgur.com/1Gjkf.gif)
Unassigned

**Comment by piperchester** [comment]
Closing this issue and moving discussion to a wiki page
