### ISSUE TITLE
Backspace

### ISSUE THREAD

**Issue by 7imbrook** [RITAccess/accessbraille#5]
finish implementing backspace

**Comment by piperchester** [comment]
Method will be implemented in the TextOut.m. Currently message is being written to screen in line #261 of BrailleTyperController.m.

**Comment by piperchester** [comment]
Possibly start using categories? See issue #15.

**Comment by piperchester** [comment]
Backspace is implemented as the removeCharacter method within TextOut.m. I've pushed the change, and for now I'm going to close this issue.
