### ISSUE TITLE
Instructions Menu

### ISSUE THREAD

**Issue by piperchester** [RITAccess/accessbraille#9]
Currently there is no screen that tells the user how to use the application. This might be helpful to first-users or people coming into the project.

**Comment by piperchester** [comment]
Looking into using InterfaceBuilder to create the instructions screen.

**Comment by piperchester** [comment]
Instructions can now be accessed from the Main Menu. Still need to add NavBar button and functionality.

**Comment by piperchester** [comment]
Am currently dynamically creating text, but having trouble with proper spacing. I tried a bulleted list but wasn't met with much success. The bullets would just display in an inline:block format.

**Comment by 7imbrook** [comment]
you can use \n to put in a newline if need be.

~Michael Timbrook
Student Researcher
Rochester Institute of Technology
Software Engineering B.S.

**Comment by piperchester** [comment]
Instructions Menu is functional. I'm closing this issue as pleasetest for future edits/tweaks.
